name: Deploy React App to S3

on:
  push:
    branches:
      - master    # main OR master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # React 프로젝트 Node 버전

      # .env 환경 변수 등록
      - name: Create .env file
        run: |
          echo "REACT_APP_MOVIE_API_KEY=${{ secrets.REACT_APP_MOVIE_API_KEY }}" > .env
          echo "REACT_APP_MOVIE_API_TOKEN=${{ secrets.REACT_APP_MOVIE_API_TOKEN }}" >> .env
          echo "REACT_APP_MOVIE_BASE_FETCH=${{ secrets.REACT_APP_MOVIE_BASE_FETCH }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: CI=false npm run build # CI=false : 경고 무시하고 빌드 (실제 운영배포 시 CI=true로 설정(생략))

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2   # 서울 리전

      - name: Deploy to S3
        run: aws s3 sync build/ s3://react-netflixclone-demo --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E2LNHKFPY2EL02 --paths "/*"